<font size = 10>使用MNE读取数据 </font>   
<font size=5>EEG Motor Movement/Imagery Dataset </font>

In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import mne
%matplotlib qt

file_path ： 原始数据保存的地址   
save_path : 预处理后文件保存地址

In [2]:
# 只读取脑电数据，不用读取事件数据
file_path=""
save_path=""
files_name_array=os.listdir(file_path)
print(len(files_name_array))

28


In [3]:
print(len(files_name_array))
print(files_name_array)

28
['S001R09.edf.event', 'S001R01.edf.event', 'S001R12.edf.event', 'S001R08.edf', 'S001R05.edf', 'S001R03.edf.event', 'S001R10.edf.event', 'S001R08.edf.event', 'S001R06.edf.event', 'S001R05.edf.event', 'S001R02.edf.event', 'S001R14.edf.event', 'S001R13.edf.event', 'S001R01.edf', 'S001R10.edf', 'S001R11.edf', 'S001R03.edf', 'S001R07.edf', 'S001R04.edf.event', 'S001R11.edf.event', 'S001R04.edf', 'S001R06.edf', 'S001R13.edf', 'S001R12.edf', 'S001R14.edf', 'S001R02.edf', 'S001R07.edf.event', 'S001R09.edf']


In [4]:
flie_name=files_name_array[27]

In [5]:
fname=file_path+"\\"+flie_name

In [6]:
print(fname)

E:\Dataset\EEG Motor MovementImagery Dataset\eeg-motor-movementimagery-dataset-1.0.0\files\S001\S001R09.edf


In [7]:
raw_data= mne.io.read_raw_edf(fname)

Extracting EDF parameters from E:\Dataset\EEG Motor MovementImagery Dataset\eeg-motor-movementimagery-dataset-1.0.0\files\S001\S001R09.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...


In [8]:
print(raw_data)
print('\n')
print(raw_data.info)

<RawEDF | S001R09.edf, 64 x 20000 (125.0 s), ~64 kB, data not loaded>


<Info | 7 non-empty values
 bads: []
 ch_names: Fc5., Fc3., Fc1., Fcz., Fc2., Fc4., Fc6., C5.., C3.., C1.., ...
 chs: 64 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 80.0 Hz
 meas_date: 2009-08-12 16:15:00 UTC
 nchan: 64
 projs: []
 sfreq: 160.0 Hz
>


In [9]:
print(raw_data.ch_names)

['Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']


In [10]:
# 只保留需要用到的通道，减少重参考的计算量，和内存占用
use_channel=['C3..', 'Cz..', 'C4..', 'Fp1.', 'Fpz.', 'Fp2.',  'F7..','F3..', 'Fz..', 'F4..', 'F8..', 'P3..',  'Pz..', 
             'P4..','O1..', 'Oz..','O2..''C3..', 'Cz..', 'C4..', 'Fp1.', 'Fpz.', 'Fp2.',  'F7..','F3..', 'Fz..', 
             'F4..', 'F8..', 'P3..',  'Pz..', 'P4..','O1..', 'Oz..', 'O2..']
use_data=raw_data.pick_channels(use_channel)

In [11]:
# 修改通道名称
rename_channel={'C3..':'C3', 'Cz..':'Cz', 'C4..':'C4', 'Fp1.':'Fp1', 'Fpz.':'Fpz', 'Fp2.':'Fp2',  'F7..':'F7',
                'F3..':'F3', 'Fz..':'Fz', 'F4..':'F4', 'F8..':'F8', 'P3..':'P3',  'Pz..':'Pz', 'P4..':'P4','O1..':'O1',
                'Oz..':'Oz', 'O2..':'O2','C3..':'C3', 'Cz..':'Cz', 'C4..':'C4',
                'Fp1.':'Fp1', 'Fpz.':"Fpz", 'Fp2.':'Fp2',  'F7..':'F7','F3..':'F3', 'Fz..':'Fz', 'F4..':'F4', 
                'F8..':'F8', 'P3..':'P3',  'Pz..':'Pz', 
                'P4..':'P4','O1..':'O1', 'Oz..':'Oz', 'O2..':'O2'}
use_data.rename_channels(rename_channel)

<RawEDF | S001R09.edf, 17 x 20000 (125.0 s), ~21 kB, data not loaded>

In [12]:
use_data.set_montage(montage="standard_1020")

<RawEDF | S001R09.edf, 17 x 20000 (125.0 s), ~30 kB, data not loaded>

In [13]:
use_copy=use_data.copy()
use_copy.load_data()

Reading 0 ... 19999  =      0.000 ...   124.994 secs...


<RawEDF | S001R09.edf, 17 x 20000 (125.0 s), ~2.6 MB, data loaded>

In [14]:
use_copy.set_eeg_reference(ref_channels='average')

EEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('EEG',) reference.


<RawEDF | S001R09.edf, 17 x 20000 (125.0 s), ~2.6 MB, data loaded>

In [15]:
# 滤波
use_copy.notch_filter(freqs=50)
use_copy.filter(l_freq=0.1,h_freq=30)

Setting up band-stop filter from 49 - 51 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 49.38
- Lower transition bandwidth: 0.50 Hz (-6 dB cutoff frequency: 49.12 Hz)
- Upper passband edge: 50.62 Hz
- Upper transition bandwidth: 0.50 Hz (-6 dB cutoff frequency: 50.88 Hz)
- Filter length: 1057 samples (6.606 sec)

Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 0.1 - 30 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 0.10
- Lower transition bandwidth: 0.10 Hz (-6 dB cutoff frequency: 0.05 Hz)
- Upper passband edge: 30.00 Hz
- Upper transition bandwidth

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    0.0s finished


<RawEDF | S001R09.edf, 17 x 20000 (125.0 s), ~2.6 MB, data loaded>

In [16]:
eeg_down=use_copy.copy().resample(sfreq=80)

In [17]:
print(eeg_down.ch_names)

['C3', 'Cz', 'C4', 'Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'P3', 'Pz', 'P4', 'O1', 'Oz', 'O2']


In [18]:
use_down = eeg_down.get_data()

In [19]:
print(use_down.shape)

(17, 10000)


In [20]:
print(use_down[:,0:3])

[[-1.53675184e-10  3.33931763e-05  2.86343024e-05]
 [ 2.15166415e-11  1.87934378e-05  7.16154131e-06]
 [-3.59536544e-10 -2.48767832e-06  1.77559062e-05]
 [-2.12404206e-10  3.20457060e-06 -1.41914219e-06]
 [ 1.60194472e-10  6.68518610e-06  8.53872270e-06]
 [-4.28402438e-10  3.80356643e-06  1.22898295e-05]
 [ 4.01000141e-10 -1.71644401e-06  5.72583429e-06]
 [-2.80809608e-10 -7.05498394e-06  5.79063639e-06]
 [-2.95617996e-10 -5.78102983e-06 -6.53603570e-06]
 [-2.98435894e-10 -6.24631080e-06  5.16952818e-06]
 [-5.24764512e-10 -1.84857337e-05  1.15216039e-05]
 [-1.34461750e-10  1.52973423e-05 -6.34355428e-06]
 [ 4.78900235e-10  7.10910879e-06 -1.76083302e-05]
 [ 3.63803093e-10  5.91301714e-06 -1.97760165e-06]
 [ 1.15226370e-10 -1.32651680e-05 -2.15453065e-05]
 [ 3.55802437e-10 -1.66542684e-05 -3.14689385e-05]
 [ 7.91664741e-10 -2.25077885e-05 -1.56889959e-05]]


In [21]:
re_sequnce=np.zeros(use_down.shape)
print(re_sequnce.shape)
re_sequnce[0,:] =use_down[3,:]
re_sequnce[1,:] =use_down[4,:]
re_sequnce[2,:] =use_down[5,:]
re_sequnce[3,:] =use_down[6,:]
re_sequnce[4,:] =use_down[7,:]
re_sequnce[5,:] =use_down[8,:]
re_sequnce[6,:] =use_down[9,:]
re_sequnce[7,:] =use_down[10,:]
re_sequnce[8,:] =use_down[0,:]
re_sequnce[9,:] =use_down[1,:]
re_sequnce[10,:]=use_down[2,:]
re_sequnce[11,:]=use_down[11,:]
re_sequnce[12,:]=use_down[12,:]
re_sequnce[13,:]=use_down[13,:]
re_sequnce[14,:]=use_down[14,:]
re_sequnce[15,:]=use_down[15,:]
re_sequnce[16,:]=use_down[16,:]


(17, 10000)


In [22]:
print(re_sequnce[:,0:3])

[[-2.12404206e-10  3.20457060e-06 -1.41914219e-06]
 [ 1.60194472e-10  6.68518610e-06  8.53872270e-06]
 [-4.28402438e-10  3.80356643e-06  1.22898295e-05]
 [ 4.01000141e-10 -1.71644401e-06  5.72583429e-06]
 [-2.80809608e-10 -7.05498394e-06  5.79063639e-06]
 [-2.95617996e-10 -5.78102983e-06 -6.53603570e-06]
 [-2.98435894e-10 -6.24631080e-06  5.16952818e-06]
 [-5.24764512e-10 -1.84857337e-05  1.15216039e-05]
 [-1.53675184e-10  3.33931763e-05  2.86343024e-05]
 [ 2.15166415e-11  1.87934378e-05  7.16154131e-06]
 [-3.59536544e-10 -2.48767832e-06  1.77559062e-05]
 [-1.34461750e-10  1.52973423e-05 -6.34355428e-06]
 [ 4.78900235e-10  7.10910879e-06 -1.76083302e-05]
 [ 3.63803093e-10  5.91301714e-06 -1.97760165e-06]
 [ 1.15226370e-10 -1.32651680e-05 -2.15453065e-05]
 [ 3.55802437e-10 -1.66542684e-05 -3.14689385e-05]
 [ 7.91664741e-10 -2.25077885e-05 -1.56889959e-05]]


In [23]:
save_name=save_path+"\\"+flie_name[0:-4]+".npy"
np.save(save_name, re_sequnce)